# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Tommy Kolkman
title: Freelance webdeveloper
email: tommy@steez.nl
website: steez.nl

# Social links
twitter_username: tommykolkman
github_username:  TommyKolkman
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: tommykolkman
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: Steez - stijlvolle, schaalbare code, pragmatisch en snel.
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Steez - plain old style with ease - zoals de [Urban Dictionary het beschrijft](https://www.urbandictionary.com/define.php?term=steez), is mijn streven in mijn projecten. Mooie, schaalbare code, pragmatisch en snel opgeleverd.

  Ik heb ruime ervaring op het gebied van (back-end) ontwikkeling in WordPress (10+ jaar) en Magento 2 (+3 jaar). Verder heb ik in mijn rol als technisch directeur / lead developer bij [Elephant](https://elephantcs.nl) veel ervaring opgedaan
  in de algemene organisatie van geavanceerde webprojecten en workflows. Deze ervaring kan ik ook goed voor u toepassen.

  Neem contact met mij op voor:
  - Back-end development voor WordPress en Magento 2
  - (Advies op het gebied van) hosting
  - Performance verbeteren
  - Consultancy: kan ik als "spreekbuis" tussen u en uw IT partij fungeren?

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
